name: Golden Mill

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    #   - name: Setup Node.js
    #     uses: actions/setup-node@v4
    #     with:
    #       node-version: '20' 
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Create .env
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > server/.env
      - name: Cache yarn for speedest install
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn
            yarn.lock
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 77.73.39.210 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh root@77.73.39.210 << 'EOF'
            set -e
            cd /var/www/goldenmill/prod
            git fetch origin master
            git reset --hard origin/master
            yarn install --frozen-lockfile
            rm -rf dist
            yarn build
            yarn generate-sitemap
            echo "Deployed commit: $(git rev-parse HEAD)"
          EOF