name: Golden Mill

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Clean up npm lock
        run: rm -f package-lock.json
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Create .env
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > server/.env

      - name: Cache yarn for speedest install
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn
            yarn.lock
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 77.73.39.210 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh root@77.73.39.210 << 'EOF'
            set -e
            cd /var/www/goldenmill/prod
            
            # Очистка и обновление кода
            git fetch origin master
            git reset --hard origin/master
            
            # Установка зависимостей
            yarn install --frozen-lockfile
            cd server && yarn install --frozen-lockfile && cd ..
            
            # Очистка старых сборок
            rm -rf dist
            rm -rf server/dist
            
            # Сборка приложения
            echo "Building main application..."
            yarn build
            yarn build:ssr
            yarn generate-sitemap
            
            # Сборка API
            echo "Building API server..."
            cd server
            yarn build
            cd ..
            
            # Остановка старых процессов
            echo "Stopping old processes..."
            pm2 stop goldenmill-ssr || true
            pm2 stop goldenmill-server || true
            pm2 delete goldenmill-ssr || true
            pm2 delete goldenmill-server || true
            
            # Запуск новых процессов
            echo "Starting new processes..."
            # Запуск API
            cd server
            pm2 start ecosystem.config.js --only goldenmill-server
            cd ..
            
            # Запуск SSR
            pm2 start ecosystem.config.js --only goldenmill-ssr
            
            # Проверка статуса
            echo "Checking process status..."
            sleep 5
            pm2 list
            
            # Проверка доступности
            echo "Checking application availability..."
            curl -f http://localhost:3005 || exit 1
            curl -f http://localhost:3002 || exit 1
            
            echo "Deployment completed successfully!"
            echo "Deployed commit: $(git rev-parse HEAD)"
          EOF